function  Data(){
    return(
        <>
            <div className="data w-full h-auto pb-10 bg-slate-700">
                <div className="about pt-5 ">
                    <h1 className="aboutme bg-lime-500 text-center h-10 text-3xl text-white ">About me</h1>
                    <h1 className="name text-lime-500 text-2xl px-10 mt-10  underline">Avinash  Sharma</h1>
                    <div className="text px-10">
                    <p className="text-white">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Error harum, eligendi molestiae consequatur vitae ea quas nesciunt recusandae quod veritatis temporibus similique, dolore labore nostrum omnis ipsam quisquam inventore. Quaerat rem nam adipisci repudiandae quasi, possimus deleniti? Exercitationem, optio. Repellat placeat cupiditate omnis animi ducimus. Reprehenderit iure doloribus rerum accusamus sit autem, iste libero placeat voluptatum in sequi repudiandae maxime explicabo atque incidunt iusto repellendus deleniti magnam, debitis accusantium perferendis asperiores! Quae soluta dolorem aliquam iste nostrum possimus! Aperiam, pariatur possimus doloremque deleniti soluta et quos magnam doloribus eveniet, nihil, magni natus. Architecto laborum doloremque quos enim, sint nihil a? Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit a voluptate similique repellat vitae nesciunt temporibus, facilis doloribus nemo magnam eius ipsam error tempore obcaecati esse labore! Autem ullam facere exercitationem architecto, porro, corrupti pariatur est quaerat nulla nemo accusamus a numquam sapiente rerum repellat eligendi fugit vel magni nam magnam cum aspernatur quasi? Dolore eum non animi voluptatibus error molestias, incidunt repudiandae qui. Quis neque beatae ea, illum mollitia quod. Amet labore laborum iusto voluptates dolorum aperiam, fugiat asperiores ipsum, fuga vero necessitatibus quod provident voluptatem inventore quos molestias facere, obcaecati quidem vel! Minima libero alias illum dolore consequatur?</p>
                    </div>
                    <h1 className="name  text-lime-500 text-2xl px-10 mt-10 underline">Avinash  Sharma</h1>
                    <div className="text px-10">
                    <p className="text-white">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Error harum, eligendi molestiae consequatur vitae ea quas nesciunt recusandae quod veritatis temporibus similique, dolore labore nostrum omnis ipsam quisquam inventore. Quaerat rem nam adipisci repudiandae quasi, possimus deleniti? Exercitationem, optio. Repellat placeat cupiditate omnis animi ducimus. Reprehenderit iure doloribus rerum accusamus sit autem, iste libero placeat voluptatum in sequi repudiandae maxime explicabo atque incidunt iusto repellendus deleniti magnam, debitis accusantium perferendis asperiores! Quae soluta dolorem aliquam iste nostrum possimus! Aperiam, pariatur possimus doloremque deleniti soluta et quos magnam doloribus eveniet, nihil, magni natus. Architecto laborum doloremque quos enim, sint nihil a? Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit a voluptate similique repellat vitae nesciunt temporibus, facilis doloribus nemo magnam eius ipsam error tempore obcaecati esse labore! Autem ullam facere exercitationem architecto, porro, corrupti pariatur est quaerat nulla nemo accusamus a numquam sapiente rerum repellat eligendi fugit vel magni nam magnam cum aspernatur quasi? Dolore eum non animi voluptatibus error molestias, incidunt repudiandae qui. Quis neque beatae ea, illum mollitia quod. Amet labore laborum iusto voluptates dolorum aperiam, fugiat asperiores ipsum, fuga vero necessitatibus quod provident voluptatem inventore quos molestias facere, obcaecati quidem vel! Minima libero alias illum dolore consequatur?</p>
                    </div>
                    <h1 className="name text-lime-500 text-2xl px-10 mt-10 underline">Avinash  Sharma</h1>
                    <div className="text px-10">
                    <p className="text-white">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Error harum, eligendi molestiae consequatur vitae ea quas nesciunt recusandae quod veritatis temporibus similique, dolore labore nostrum omnis ipsam quisquam inventore. Quaerat rem nam adipisci repudiandae quasi, possimus deleniti? Exercitationem, optio. Repellat placeat cupiditate omnis animi ducimus. Reprehenderit iure doloribus rerum accusamus sit autem, iste libero placeat voluptatum in sequi repudiandae maxime explicabo atque incidunt iusto repellendus deleniti magnam, debitis accusantium perferendis asperiores! Quae soluta dolorem aliquam iste nostrum possimus! Aperiam, pariatur possimus doloremque deleniti soluta et quos magnam doloribus eveniet, nihil, magni natus. Architecto laborum doloremque quos enim, sint nihil a? Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit a voluptate similique repellat vitae nesciunt temporibus, facilis doloribus nemo magnam eius ipsam error tempore obcaecati esse labore! Autem ullam facere exercitationem architecto, porro, corrupti pariatur est quaerat nulla nemo accusamus a numquam sapiente rerum repellat eligendi fugit vel magni nam magnam cum aspernatur quasi? Dolore eum non animi voluptatibus error molestias, incidunt repudiandae qui. Quis neque beatae ea, illum mollitia quod. Amet labore laborum iusto voluptates dolorum aperiam, fugiat asperiores ipsum, fuga vero necessitatibus quod provident voluptatem inventore quos molestias facere, obcaecati quidem vel! Minima libero alias illum dolore consequatur?</p>
                    </div>
                </div>
            </div>
        </>
    )
}
export default Data